services:
  # Container Database
  db-donasi:
    image: mysql:8.0
    container_name: mysql-donasi
    restart: always
    environment:
      MYSQL_DATABASE: db_donasikita
      MYSQL_ROOT_PASSWORD: donasikita
    volumes:
      - db_data:/var/lib/mysql

  # Container Aplikasi (Project DonasiKita)
  app-donasi:
    image: donasi-app:latest
    container_name: running-donasi
    restart: always
    ports:
      - "80:80"
    depends_on:
      - db-donasi
    environment:
      - DB_HOST=db-donasi
      - DB_DATABASE=db_donasikita
      - DB_USERNAME=root
      - DB_PASSWORD=donasikita

  # Container phpMyAdmin untuk manajemen database
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: pma-donasikita
    restart: always
    ports:
      - "8081:80" # Kami gunakan port 8081 agar tidak bentrok dengan Jenkins (8080)
    environment:
      - PMA_HOST=db-donasi    # Menghubungkan ke container database
      - PMA_USER=root         # Username root MySQL
      - PMA_PASSWORD=donasikita # Password yang Anda buat sebelumnya
    depends_on:
      - db-donasi

volumes:
  db_data:

